pipelines:
  - name: releaseTest_nodepool
    configuration:
      nodePool: releaseTest_nodepool                       # Run in the dynamic node pool on AWS
    steps:
      - name: nodePool_step1
        type: Bash
        execution:
          onExecute:
            - echo "$step_name is running in $step_platform on $step_node_pool_name"
 
      - name: nodePool_step2
        type: Bash
        configuration:
          inputSteps:
            - name: nodePool_step1
        execution:
          onExecute:
            - echo "$step_name is running in $step_platform on $step_node_pool_name"

      - name: nodePool_step3
        type: Bash
        configuration:
          inputSteps:
            - name: nodePool_step1
        execution:
          onExecute:
            - echo "$step_name is running in $step_platform on $step_node_pool_name"
